name: Setup yarn and node project
description: Bootstrap a Node project with yarn

inputs:
  use-lfs:
    required: true
    default: false
  node-version:
    default: "14.15.4"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        lfs: ${{ inputs.use-lfs }}

    - if: ${{ inputs.use-lfs }}
      run: git lfs checkout

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn

    - name: Check Yarn cache hit
      run: echo "Yarn cache hit: ${{ steps.yarn-cache.outputs.cache-hit }}"

    - name: Install dependencies
      run: yarn --prefer-offline --frozen-lockfile # https://stackoverflow.com/a/62244232/5945418

